### ISSUE TITLE
Unable to read Pokemon Scarlet/Violet DLC Pokemon?

### ISSUE THREAD

**Issue by UsRnM44** [arleypadua/PKHeX.Everywhere#110] opened 2024-12-06 00:15 UTC
Currently playing through the second DLC of Pokemon Violet, and when trying to use the Web PKHeX, if I have Pokemon in Box or in Party that are not in the base game, it shows me this error:
<img width="1787" alt="Screenshot 2024-12-06 at 2 12 45" src="https://github.com/user-attachments/assets/fa038a51-44f8-4b86-92df-18faadcb1be3">

**Comment by arleypadua** [comment] 2024-12-06 07:58
Interesting.. it would be useful to have the full details of the message

Can you copy here everything that's shown when you click on "Clock here to file an issue"

**Comment by UsRnM44** [comment] 2024-12-06 09:57
> Interesting.. it would be useful to have the full details of the message
> 
> Can you copy here everything that's shown when you click on "Clock here to file an issue"

This is the link it gives me

https://github.com/arleypadua/PKHeX.Everywhere/issues/new?title=Error%20on%20PKHeX.Web%3A%20ArgumentOutOfRange_IndexMustBeLess%20Arg_ParamName_Name%2C%20index&body=%23%20Error%20on%20PKHeX.Web%0A%0A%2A%20%2A%2AId%2A%2A%3A%20b5c5f933-60d3-464b-995a-72d73598ecc8%0A%2A%20%2A%2AGame%20version%2A%2A%3A%20Violet%0A%2A%20%2A%2AGeneration%2A%2A%3A%20Gen9%0A%23%23%20Type%0A%60%60%60%0AArgumentOutOfRangeException%0A%60%60%60%0A%0A%23%23%20Message%0A%60%60%60%0AArgumentOutOfRange_IndexMustBeLess%20Arg_ParamName_Name%2C%20index%0A%60%60%60%0A%0A%23%23%20Stack%20trace%0A%60%60%60%0A%20%20%20at%20PKHeX.Core.FormConverter.GetFormsGen6%28UInt16%20species%2C%20IReadOnlyList%601%20types%2C%20IReadOnlyList%601%20forms%2C%20IReadOnlyList%601%20genders%2C%20Byte%20generation%29%0A%20%20%20at%20PKHeX.Core.FormConverter.GetFormList%28UInt16%20species%2C%20IReadOnlyList%601%20types%2C%20IReadOnlyList%601%20forms%2C%20IReadOnlyList%601%20genders%2C%20EntityContext%20context%29%0A%20%20%20at%20PKHeX.Facade.Repositories.FormRepository.GetFor%28Species%20species%2C%20EntityContext%20context%29%0A%20%20%20at%20PKHeX.Facade.Repositories.FormRepository.GetFor%28PKM%20pokemon%29%0A%20%20%20at%20PKHeX.Facade.Pokemons.PokemonForm.get_Form%28%29%0A%20%20%20at%20PKHeX.Web.Components.PokemonTable.%3C%3Ec__DisplayClass0_0.%3CBuildRenderTree%3Eb__4%28RenderTreeBuilder%20__builder3%29%0A%20%20%20at%20Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder.AddContent%28Int32%20%2C%20RenderFragment%20%29%0A%20%20%20at%20AntDesign.Column%601%5B%5BPKHeX.Facade.Repositories.SpeciesDefinition%2C%20PKHeX.Facade%2C%20Version%3D1.0.0.0%2C%20Culture%3Dneutral%2C%20PublicKeyToken%3Dnull%5D%5D.%3CBuildRenderTree%3Eb__170_0%28RenderTreeBuilder%20__builder2%29%0A%20%20%20at%20Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder.AddContent%28Int32%20%2C%20RenderFragment%20%29%0A%20%20%20at%20Microsoft.AspNetCore.Components.CascadingValue%601%5B%5BSystem.Boolean%2C%20System.Private.CoreLib%2C%20Version%3D9.0.0.0%2C%20Culture%3Dneutral%2C%20PublicKeyToken%3D7cec85d7bea7798e%5D%5D.Render%28RenderTreeBuilder%20builder%29%0A%20%20%20at%20Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch%28RenderBatchBuilder%20%2C%20RenderFragment%20%2C%20Exception%26%20%29%0A%60%60%60&labels=bug

**Comment by arleypadua** [comment] 2024-12-06 10:09
Yup, that contains all information I need

Thanks 🙏

**Comment by arleypadua** [comment] 2024-12-06 19:52
this is actually a duplicate of this one: https://github.com/arleypadua/PKHeX.Everywhere/issues/72

will release a new version fixing it in a bit

**Closed by arleypadua** 2024-12-06 19:52 UTC
