### ISSUE TITLE
Error on PKHeX.Web: Expected 1-6, got 0 Arg_ParamName_Name, value

### ISSUE THREAD

**Issue by ken173** [arleypadua/PKHeX.Everywhere#75] opened 2024-08-31 12:17 UTC
# Error on PKHeX.Web

* **Id**: 4ef4e7b8-a98f-44b6-8302-3a42f5bad8e1
* **Game version**: Alpha Sapphire
* **Generation**: Gen6
## Type
```
ArgumentOutOfRangeException
```

## Message
```
Expected 1-6, got 0 Arg_ParamName_Name, value
```

## Stack trace
```
   at PKHeX.Core.SaveFile.set_PartyData(IList`1 value)
   at PKHeX.Facade.PokemonParty.Commit()
   at PKHeX.Facade.Trainer.Commit()
   at PKHeX.Facade.Game.ToByteArray()
   at PKHeX.Web.Services.GameService.Export()
   at PKHeX.Web.Components.LoadGameComponent.ExportSaveAsync()
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at AntDesign.Button.HandleOnClick(MouseEventArgs args)
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task , ComponentState )
```

**Comment by arleypadua** [comment] 2024-08-31 13:02
Is this error happening out of a save file you loaded or an empty one?

If you tried to export an empty save file, then it's a known issue

**Comment by ken173** [comment] 2024-08-31 13:33
It's happening with a loaded save file.

**Comment by arleypadua** [comment] 2024-09-04 16:18
I can't seem to reproduce the issue. Do you mind sharing your save file here so I can have a look?

**Comment by arleypadua** [comment] 2024-09-24 18:32
Closing as I'm not able to reproduce

**Closed by arleypadua** 2024-09-24 18:32 UTC
Labels: bug
