### ISSUE TITLE
Manual changing Money does not work 

### ISSUE THREAD

**Issue by Awetspoon** [arleypadua/PKHeX.Everywhere#96] opened 2024-11-16 01:14 UTC
trying to change the money manually by typing 9999999 rests back to the orignal money you left off. using the arrow up and down next to the money works but is very slow. many thanks Marcus

**Comment by arleypadua** [comment] 2024-11-18 19:10
Will have a look as soon as I find some free time :)

Thanks for reporting

**Comment by arleypadua** [comment] 2024-11-29 18:41
I cannot reproduce the same issue, even if I overflow with as many `9` digits as I want, it sets back to the maximum allowed as expected.

Can you try again on a different browser?

**Comment by Awetspoon** [comment] 2024-11-29 22:00
After I ask about the issue sorry for some reason after closing it and
reopen the issue was sorted. Was weird because I tried like 6x 😂. Thank
you for looking into it much appreciated

**Comment by arleypadua** [comment] 2024-11-29 22:11
Thanks for the feedback, will close it for now

**Closed by arleypadua** 2024-11-29 22:11 UTC
Labels: bug, not reproducible
